GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJSaGFsYXN5YSIsImVtYWlsIjoiZWxlbnJoYWxzeWFAZ21haWwuY29tIiwiaWF0IjoxNzMyNzI3MTgxLCJleHAiOjE3MzI3MjcyNDF9.39rUHXoKQedbyFxcCUFcAzDb-E9oS-WypPxkG4iODbM
###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Rhalasya",
    "email": "elenrhalsya@gmail.com",
    "password": "12345",
    "confPassword": "12345"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "elenrhalsya@gmail.com",
    "password": "12345"
}


###
GET http://localhost:5000/token


###
DELETE http://localhost:5000/logout